{{- range $componentName, $component := .Values.app8.components }}
{{- if and $component.ingress (ne $component.enabled false) (ne $component.ingress.enabled false) }}
{{- $componentDict := (dict "global" $ "component" $component "componentName" $componentName "Chart" $.Chart "Release" $.Release ) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "componentName" $componentDict }}
  labels:
    {{- include "labels" $componentDict | nindent 4 }}
    {{- with $component.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $component.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $component.ingress.className }}
  ingressClassName: {{ $component.ingress.className }}
  {{- end }}
  {{- with $component.ingress.defaultBackend }}
  defaultBackend:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $component.ingress.rules }}
  rules:
  {{- include "ingressRules" . | nindent 2 }}
  {{- end }}
  {{- with $component.ingress.tls }}
  tls:
  {{- include "ingressTLS" . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
